"""create core persistence schema

Revision ID: 0b2d23cf6e29
Revises:
Create Date: 2026-09-28 23:09:25.372264
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0b2d23cf6e29"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("google_subject", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("google_subject"),
    )
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("session_token_digest", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_token_digest"),
    )
    op.create_index(op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sources_owner_id"), "sources", ["owner_id"], unique=False)
    op.create_table(
        "source_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("version_number > 0", name="ck_source_versions_positive_number"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "version_number", name="uq_source_versions_source_number"),
    )
    op.create_index(
        op.f("ix_source_versions_source_id"), "source_versions", ["source_id"], unique=False
    )
    op.create_table(
        "source_segments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_version_id", sa.Integer(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("locator", sa.String(length=255), nullable=False),
        sa.Column("segment_text", sa.Text(), nullable=False),
        sa.CheckConstraint("ordinal > 0", name="ck_source_segments_positive_ordinal"),
        sa.ForeignKeyConstraint(["source_version_id"], ["source_versions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_version_id", "locator", name="uq_source_segments_version_locator"
        ),
        sa.UniqueConstraint(
            "source_version_id", "ordinal", name="uq_source_segments_version_ordinal"
        ),
    )
    op.create_index(
        op.f("ix_source_segments_source_version_id"),
        "source_segments",
        ["source_version_id"],
        unique=False,
    )
    op.create_table(
        "transformation_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("source_version_id", sa.Integer(), nullable=False),
        sa.Column("supporting_context", sa.Text(), nullable=False),
        sa.Column("audience", sa.String(length=120), nullable=False),
        sa.Column("tone", sa.String(length=80), nullable=False),
        sa.Column("language", sa.String(length=80), nullable=False),
        sa.Column("detail_level", sa.String(length=20), nullable=False),
        sa.Column("objective", sa.String(length=160), nullable=False),
        sa.Column("style", sa.String(length=120), nullable=False),
        sa.Column("selected_output_types", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_version_id"], ["source_versions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transformation_runs_owner_id"), "transformation_runs", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_transformation_runs_source_version_id"),
        "transformation_runs",
        ["source_version_id"],
        unique=False,
    )
    op.create_table(
        "artifact_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transformation_run_id", sa.Integer(), nullable=False),
        sa.Column("output_type", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed')",
            name="ck_artifact_runs_status",
        ),
        sa.ForeignKeyConstraint(
            ["transformation_run_id"], ["transformation_runs.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_artifact_runs_transformation_run_id"),
        "artifact_runs",
        ["transformation_run_id"],
        unique=False,
    )
    op.create_table(
        "artifact_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artifact_run_id", sa.Integer(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("source_version_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(length=120), nullable=True),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("prompt_version", sa.String(length=120), nullable=True),
        sa.Column("prompt_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("version_number > 0", name="ck_artifact_versions_positive_number"),
        sa.ForeignKeyConstraint(["artifact_run_id"], ["artifact_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_version_id"], ["source_versions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "artifact_run_id", "version_number", name="uq_artifact_versions_run_number"
        ),
    )
    op.create_index(
        op.f("ix_artifact_versions_artifact_run_id"),
        "artifact_versions",
        ["artifact_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_artifact_versions_source_version_id"),
        "artifact_versions",
        ["source_version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_artifact_versions_source_version_id"), table_name="artifact_versions")
    op.drop_index(op.f("ix_artifact_versions_artifact_run_id"), table_name="artifact_versions")
    op.drop_table("artifact_versions")
    op.drop_index(op.f("ix_artifact_runs_transformation_run_id"), table_name="artifact_runs")
    op.drop_table("artifact_runs")
    op.drop_index(
        op.f("ix_transformation_runs_source_version_id"), table_name="transformation_runs"
    )
    op.drop_index(op.f("ix_transformation_runs_owner_id"), table_name="transformation_runs")
    op.drop_table("transformation_runs")
    op.drop_index(op.f("ix_source_segments_source_version_id"), table_name="source_segments")
    op.drop_table("source_segments")
    op.drop_index(op.f("ix_source_versions_source_id"), table_name="source_versions")
    op.drop_table("source_versions")
    op.drop_index(op.f("ix_sources_owner_id"), table_name="sources")
    op.drop_table("sources")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_table("users")
    # ### end Alembic commands ###
